import { Request, Response } from 'express'
import { GoogleSpreadsheet } from 'google-spreadsheet'
import { StatusCodes } from 'http-status-codes'

const getGeneralContactSheet = async () => {
  const doc = new GoogleSpreadsheet(process.env.GSHEET_ID_CONTACTS)

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL ?? '',
    private_key: (process.env.GOOGLE_PRIVATE_KEY ?? '').replace(/\\n/g, '\n'),
  })

  await doc.loadInfo()

  return doc.sheetsByIndex[0]
}
export const addContact = async (req: Request, res: Response) => {
  const { email, type } = req.body

  const gsheet = await getGeneralContactSheet()
  await gsheet.addRows([
    {
      email,
      type,
    },
  ])

  return res.status(StatusCodes.OK).send()
}
