import * as sqlite3 from 'sqlite3';

import * as sqlite3Wrapper from '../../utils/sqliteWrapper';

// A test function to be replaced with
// an engine for dynamic DB query generated by LLM
export async function printDBTableNames(
  db: sqlite3.Database
): Promise<string[]> {
  const q = `
  SELECT 
    name 
  FROM 
    sqlite_master 
  WHERE 
    type='table' 
  ORDER BY 
    name
  `;
  return sqlite3Wrapper.allP(db, q);
}
