name: App - Test

on:
  push:
    paths:
      - 'app/**'
      - '.pretterrc'
      - 'eslint-config/**'

defaults:
  run:
    working-directory: ./app/

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.15

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000
        env:
          PALETTE_ASSET_KEY: ${{ secrets.PALETTE_ASSET_KEY }}

      - name: Package, Typecheck, and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PALETTE_ASSET_KEY: ${{ secrets.PALETTE_ASSET_KEY }}
        run: |
          yarn package
          yarn tsc
          yarn test

      - name: Lint
        run: |
          yarn lint
